const mongoose = require('mongoose')


// Email validation 


function validateEmail(email) {
   let regex =  /^[^\s@]+@[^\s@]+$/

   //let regex = new RegExp('/^[^\s@]+@[^\s@]+$/');

    if(regex.test(email)) {
        return true
    }
    else {
        return false
    }
}

// Database schema, id autogenerated

const employeeSchema = new mongoose.Schema({
    
    firstName: {
        type:String,
        required: true,
        trim: true
    },
    lastName: {
        type:String,
        required: true,
        trim: true

    },
    emailId: {
        type:String,
        validate(value) {
            if(!validateEmail(value)) throw new Error("Email not valid format")
        }
    }
})

const Employee = mongoose.model("employee", employeeSchema, "employee");

module.exports = Employee